version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pqc-network

  oqs-provider:
    image: openquantumsafe/oqs-ossl3:latest
    ports:
      - "4433:4433"
    networks:
      - pqc-network
    command: /bin/sh -c "tail -f /dev/null"

networks:
  pqc-network:
    driver: bridge
